name: CI-Workflow

on:
  push:
    branches:
      - "main"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: actions/cache@v3
        id: npm-cache
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}-{{ checksum "patches.hash" }}
      - name: Install packages
        run: pnpm install
  frontend-build:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: frontend build
        run: pnpm frontend dev
        env:
          CI: false
          NEXT_PUBLIC_CLIENT_ID: ${{secrets.NEXT_PUBLIC_CLIENT_ID}}
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./pkgs/frontend/.next"
